server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: alumno-route
          uri: lb://alumno-service
          predicates:
            - Path=/api/alumnos/**
        - id: escuela-route
          uri: lb://escuela-service
          predicates:
            - Path=/api/escuelas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
